### ISSUE TITLE
Add VR examples to this DOTS Repo

### ISSUE THREAD

**Issue by castana1962** [keijiro/Voxelman#10]
Hi
I am working with VR projects and I am very interested in learning DOTS to use it in my own VR ones to optimize PC 3D Assets and Performance for VR devices ( mainly Oculus Quest), for it, Could you add any VR examples to this repo?
Thanks for your time
Alejandro Castan

**Comment by keijiro** [comment]
Unfortunately, there are two problems:

- I have no experience about VR.
- This repository is outdated. It's not compatible with the latest version of DOTS. Actually, DOTS/ECS was changed greatly after I wrote this sample, so I have to rewrite most part of this project to adapt to the latest version.

I'd recommend referring other samples for learning DOTS/VR.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
