### ISSUE TITLE
Cannot run in Unity2019

### ISSUE THREAD

**Issue by footman136** [keijiro/Voxelman#11]
I upgraded the code to Unity2019, but got an error mesage like this:

Library\PackageCache\com.unity.multiplayer-hlapi@1.0.4\Runtime\NetworkTransform.cs(293,20): error CS1069: The type name 'Rigidbody2D' could not be found in the namespace 'UnityEngine'. This type has been forwarded to assembly 'UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Physics 2D' in the Package Manager window to fix this error.

And I checked the unity, but in my Package Manager Window, there is no "Physics 2D" built-in package, but only "Physics" which means physics of 3D.
![无标题](https://user-images.githubusercontent.com/51815133/61760521-689e1600-adfe-11e9-8ac6-a8c3908ddc7a.png)

How can I load 'Physics 2D' into the Package Manager Window?

**Comment by keijiro** [comment]
This project is not compatible with the latest version of Unity and DOTS (formerly named ECS), and I'm not very motivated to fix it because:

- This example is not actually a good example of use of DOTS.
- DOTS is developing and changing really fast; It's not that easy to catch up.
- VFX Graph came out; It's very good at doing this kind of effects.

So, I strongly recommend referring other examples.

**Comment by footman136** [comment]
Thank you for your reply.
And I used it into my old Unity2018, there is no error this time, but I saw nothing when running. I found some missing prefabs in the scene, is that the reason? 
![无标题2](https://user-images.githubusercontent.com/51815133/61762035-3f33b900-ae03-11e9-8261-76c8f0d0e801.png)
I'm using Unity2018.2.10f1.

**Comment by keijiro** [comment]
Please check if the git submodules are correctly cloned.

**Comment by footman136** [comment]
Thank you so much! It runs on my machine now. It's so cool. 
After I download all the four submodules into my packages directory, it runs like flying.
![无标题2](https://user-images.githubusercontent.com/51815133/61763353-b8cda600-ae07-11e9-8648-223d20d23ba0.png)
