### ISSUE TITLE
Null Mesh?

### ISSUE THREAD

**Issue by KDevS** [keijiro/Voxelman#12]
I am getting a blank screen and the following error on Unity 2018.4.5f1:

`ArgumentNullException: Value cannot be null.
Parameter name: mesh
UnityEngine.Graphics.DrawMeshInstanced (UnityEngine.Mesh mesh, System.Int32 submeshIndex, UnityEngine.Material material, UnityEngine.Matrix4x4[] matrices, System.Int32 count, UnityEngine.MaterialPropertyBlock properties, UnityEngine.Rendering.ShadowCastingMode castShadows, System.Boolean receiveShadows, System.Int32 layer, UnityEngine.Camera camera, UnityEngine.Rendering.LightProbeUsage lightProbeUsage, UnityEngine.LightProbeProxyVolume lightProbeProxyVolume) (at C:/buildslave/unity/build/Runtime/Export/Graphics.cs:415)
UnityEngine.Graphics.DrawMeshInstanced (UnityEngine.Mesh mesh, System.Int32 submeshIndex, UnityEngine.Material material, UnityEngine.Matrix4x4[] matrices, System.Int32 count, UnityEngine.MaterialPropertyBlock properties, UnityEngine.Rendering.ShadowCastingMode castShadows, System.Boolean receiveShadows) (at C:/buildslave/unity/build/Runtime/Export/Graphics_BindingsOverloads.cs:179)
Unity.Rendering.MeshInstanceRendererSystem.OnUpdate () (at Library/PackageCache/com.unity.entities@0.0.12-preview.8/Unity.Rendering.Hybrid/MeshInstanceRendererSystem.cs:78)
Unity.Entities.ComponentSystem.InternalUpdate () (at Library/PackageCache/com.unity.entities@0.0.12-preview.8/Unity.Entities/ComponentSystem.cs:294)
Unity.Entities.ScriptBehaviourManager.Update () (at Library/PackageCache/com.unity.entities@0.0.12-preview.8/Unity.Entities/ScriptBehaviourManager.cs:82)
Unity.Entities.ScriptBehaviourUpdateOrder+DummyDelagateWrapper.TriggerUpdate () (at Library/PackageCache/com.unity.entities@0.0.12-preview.8/Unity.Entities/ScriptBehaviourUpdateOrder.cs:734)`

All the modules are in place and I can see the Neo prefabs in the hierarchy as well.

**Comment by keijiro** [comment]
I don't recommend using this project as a reference. ECS/DOTS has been changed greatly, so that this project is not useful any more.

If you still want to try this project, could you check if it reproduces on Unity 2018.2? I guess there are compatibility breaks between 2018.2 and 2018.4.

**Comment by KDevS** [comment]
You are correct. The problem was in the way they changed the ECS/DOTS implementations across the versions. I installed 2018.2.0f2 and it worked perfectly. Thanks for sharing the wonderful projects btw.

**Comment by keijiro** [comment]
Updated.
