### ISSUE TITLE
Unable to run this project

### ISSUE THREAD

**Issue by AhrenLi** [keijiro/Voxelman#14]
Hello, I can't run this project with unity2018.2.21f1 according to the readme file.

Prompt: script compilation error, script missing, and prefabrication missing.

**Comment by keijiro** [comment]
It seems that there is a compatibility issue with the burst compiler. Please try 2018.2.0. You can download it from this page: https://unity3d.com/unity/whats-new/unity-2018.2.0

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
