### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by andywatts** [keijiro/Voxelman#15]
Please can you add a license?  
MIT or Unity Companion would be great.

I would like to use in a loading screen of my indie game.

**Comment by keijiro** [comment]
By the way, do you know that this project is not compatible with the latest version of ECS? Did you fix the problem by yourself?

**Comment by andywatts** [comment]
Not updated voxelman, but somewhat comfortable updating dots queries and jobs to 0.8.
If you add a license, I’ll give it a go and reshare.

**Comment by keijiro** [comment]
Added LICENSE. https://github.com/keijiro/Voxelman/commit/5f65ffdfa61435ea0492e540dbf10e48645cf803

**Comment by keijiro** [comment]
Please note that this license only affects assets contained in this repository (cmu-mocap is not included).
