### ISSUE TITLE
Version updates?

### ISSUE THREAD

**Issue by sterling000** [keijiro/Voxelman#16]
Hey,

Found this just now and think it looks awesome, any plans to update to latest ECS/Unity version? The unity version of the project currently isn't even an LTS version and the burst package in the manifest isn't available on the package manager from what I can tell.

If not because you've moved on, any help in getting things to compile and run would be great (the ReadMe does say 2018.2 or later and the "or later" portion of that seems to be an issue.

**Comment by keijiro** [comment]
> the ReadMe does say 2018.2 or later and the "or later" portion of that seems to be an issue.

Correct. The "or later" portion was a problem. I didn't think that ECS would have lots of compatibility-breaking changes at the point when I wrote this example. I'd admit that I was too optimistic.

My current plan is that I will rewrite all the ECS example when it gets "stable" ("no more compatibility-breaking change state"). I don't have a firm idea about when it will be ready, though.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
