### ISSUE TITLE
Submodule permissions are denied

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [keijiro/Voxelman#3]
It seems like the submodules may not be public or open for pulling as I init the submodules locally, but was denied permission when attempting to update them.

**Comment by keijiro** [comment]
I guess that it's HTTPS vs SSH problem. I prefer using SSH over HTTPS, so .gitmodules has SSH URLs. If you're using HTTP, please try changing them to HTTPS.

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.
