### ISSUE TITLE
FPS below 10 on macbook pro

### ISSUE THREAD

**Issue by growold** [keijiro/Voxelman#4]
I test this project on windows is ok. but when I run it on macbook pro, the FPS is very low. If I change the scanner resolution to 40X40, FPS increase to 30.
![image](https://user-images.githubusercontent.com/1187526/39735158-dcbb08ee-52ac-11e8-800b-b7bdf44c2558.png)

OS version: OSX High Sierra
Unity version: 2018.1

**Comment by GilbertoGojira** [comment]
I confirm this behaviour on MacBook Pro using Unity 2018.2.0f2

**Comment by keijiro** [comment]
Unfortunately, the performance of this project is quite bad on OS X for several reasons. I'd like to update if I come up with an idea for optimization (so far, no luck).

**Comment by ROBYER1** [comment]
Macs not running something in a game engine smoothly? No surprise!

**Comment by 01GOD** [comment]
Seems this "issue" should be posted on Apple.com. Haha. If only Apple and Nvidia would kiss and be friends again. 

Likely going to be testing how XCode runs in a VM on Windows soon so I can jump ship to an OS that is fully compatible with Nvidia cards.

**Comment by keijiro** [comment]
Maybe not reproducible with 2022 LTS and Entities 1.0.
