### ISSUE TITLE
Used Git For Windows Bash Shell.   Denied. Perms?

### ISSUE THREAD

**Issue by twobob** [keijiro/Voxelman#5]
$ git submodule update
Cloning into 'D:/REPOS/Voxelman/Packages/jp.keijiro.cmu-mocap'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keijiro/CMUMocap.git' into submodule path 'D:/REPOS/Voxelman/Packages/jp.keijiro.cmu-mocap' failed
Failed to clone 'Packages/jp.keijiro.cmu-mocap'. Retry scheduled
Cloning into 'D:/REPOS/Voxelman/Packages/jp.keijiro.klak'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keijiro/Klak.git' into submodule path 'D:/REPOS/Voxelman/Packages/jp.keijiro.klak' failed
Failed to clone 'Packages/jp.keijiro.klak'. Retry scheduled
Cloning into 'D:/REPOS/Voxelman/Packages/jp.keijiro.neolowman'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keijiro/NeoLowMan.git' into submodule path 'D:/REPOS/Voxelman/Packages/jp.keijiro.neolowman' failed
Failed to clone 'Packages/jp.keijiro.neolowman'. Retry scheduled
Cloning into 'D:/REPOS/Voxelman/Packages/jp.keijiro.test-assets'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keijiro/jp.keijiro.test-assets.git' into submodule path 'D:/REPOS/Voxelman/Packages/jp.keijiro.test-assets' failed
Failed to clone 'Packages/jp.keijiro.test-assets'. Retry scheduled
Cloning into 'D:/REPOS/Voxelman/Packages/jp.keijiro.cmu-mocap'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keijiro/CMUMocap.git' into submodule path 'D:/REPOS/Voxelman/Packages/jp.keijiro.cmu-mocap' failed
Failed to clone 'Packages/jp.keijiro.cmu-mocap' a second time, aborting

The git works with other repos.

**Comment by keijiro** [comment]
It requires connecting with SSH. Please try setting a SSH key to GitHub.

https://help.github.com/articles/connecting-to-github-with-ssh/

I'm closing the issue. Please feel free to reopen if it still causes the same problem.
