### ISSUE TITLE
Burst cannot compile

### ISSUE THREAD

**Issue by koseyile** [keijiro/Voxelman#6]
![issue](https://user-images.githubusercontent.com/3655222/42560271-da1bed20-8528-11e8-91cd-4ac7484f4003.png)

Burst cannot compile.

**Comment by keijiro** [comment]
Thanks for the report. Well, I haven't maintained this project for a while. It should be updated with 2018.2.

**Comment by keijiro** [comment]
Fixed in the latest commit.

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen if it still reproduces.
