### ISSUE TITLE
Compile Error under Entities 0.0.12 preview 19

### ISSUE THREAD

**Issue by RalphC** [keijiro/Voxelman#7]
TransformMatrix renamed to LocalToWorld
signature of Schedule() changed
GetAllUniqueSharedComponentDatas() renamed to GetAllUniqueSharedComponentData()
Missing script on gameobject Voxelman/ECS/Scanner

**Comment by keijiro** [comment]
Updated. Use Unity 2022 LTS and Entities 1.0.
